{{- if .Values.serviceAccount.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "chart-sentinel.fullname" . }}
  labels:
    {{- include "chart-sentinel.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "chart-sentinel.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "chart-sentinel.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
