{{- if and (.Values.server.metricsPort) (ne .Values.server.metricsPort .Values.server.port) }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart-sentinel.fullname" . }}-metrics
  labels:
    {{- include "chart-sentinel.labels" . | nindent 4 }}
    component: metrics
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: metrics
      protocol: TCP
      name: http
  selector:
    {{- include "chart-sentinel.selectorLabels" . | nindent 4 }}
{{- end }}