{{- if .Values.serviceAccount.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "argocd-source-tracker.fullname" . }}
  labels:
    {{- include "argocd-source-tracker.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "argocd-source-tracker.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "argocd-source-tracker.serviceAccountName" . }}
  namespace: {{ Release.Namespace }}
{{- end }}
